### 서비스의 인증 키를 등록합니다
POST {{api}}/v1/service/TWEETER/authentication/key
Content-Type: application/json

{
    "apiKey": "api-key",
    "description": "트위터 API 키"
}


### 서비스의 인증 키 정보를 수정합니다
PATCH {{api}}/v1/service/TWEETER/authentication/key
Content-Type: application/json

{
    "apiKey": "api-key",
    "description": "트위터 API 키",
    "status": "ENABLED"
}


### 서비스의 인증 키 정보를 조회합니다
GET {{api}}/v1/authentication/key
X-Story-Api-Key: api-key
