### 서비스의 인증 키를 등록합니다
POST {{api}}/v1/authentications/api-keys/api-key1
Content-Type: application/json
X-Story-Api-Key: {{AUTHENTICATION_KEY}}

{
    "description": "트위터 Internal API 키"
}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}



### 서비스의 인증 키 정보를 수정합니다
PATCH {{api}}/v1/authentications/api-keys/api-key
Content-Type: application/json
X-Story-Api-Key: {{AUTHENTICATION_KEY}}

{
    "description": "트위터 API 키",
    "status": "DISABLED"
}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}


### 서비스의 인증 키 정보를 조회합니다
GET {{api}}/v1/authentications/api-key
X-Story-Api-Key: {{AUTHENTICATION_KEY}}


> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
        client.global.set("WORKSPACE_ID", response.body["result"]["workspace"]["workspaceId"])
    });
%}
