### 피드 설정 연결
POST {{api}}/v1/feeds/timeline/connect/posts/account-post/to/subscriptions/follow
Content-Type: application/json
X-Story-Api-Key: {{AUTHENTICATION_KEY}}

{
    "description": "계정 포스트 생성시 팔로워들에게 피드 발행"
}
