### 피드 설정 연결
POST {{api}}/v1/feeds/timeline/mappings/subscriptions/follow/to/subscriptions/follow
Content-Type: application/json
X-Story-Api-Key: {{AUTHENTICATION_KEY}}

{
    "description": "구독시 구독자에게 피드 발행"
}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}


### 피드 설정 연결 해제
DELETE {{api}}/v1/feeds/timeline/mappings/subscriptions/follow/to/subscriptions/follow
Content-Type: application/json
X-Story-Api-Key: {{AUTHENTICATION_KEY}}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}


### 피드 설정 목록 확인
GET {{api}}/v1/feeds/timeline/mappings/subscriptions/follow?pageSize=10
X-Story-Api-Key: {{AUTHENTICATION_KEY}}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}
