### 피드 설정 연결
POST {{api}}/v1/feeds/timeline/connect/subscriptions/follow/to/subscriptions/follow
Content-Type: application/json
X-Story-Api-Key: {{AUTHENTICATION_KEY}}

{
    "description": "구독시 구독자에게 피드 발행"
}
