### 피드 조회
GET {{api}}/v1/resources/feeds/components/timeline/subscribers/{{KITTO_USER_ID}}?pageSize=30
X-Story-Api-Key: {{AUTHENTICATION_KEY}}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}



### 피드 삭제
DELETE {{api}}/v1/resources/feeds/components/timeline/subscribers/{{KITTO_USER_ID}}/feeds/71627881039622144
X-Story-Api-Key: {{AUTHENTICATION_KEY}}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}

