### 피드 조회
GET {{api}}/v1/resources/feeds/components/timeline/subscriber/{{TARGET_ID}}?pageSize=30
X-Story-Api-Key: {{AUTHENTICATION_KEY}}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}



### 피드 삭제
DELETE {{api}}/v1/resources/feeds/components/timeline/subscriber/{{TARGET_ID}}/feeds/{FEED_ID}
X-Story-Api-Key: {{AUTHENTICATION_KEY}}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}

