spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-core.yml
    - classpath:/application-kafka.yml
    - classpath:/application-cassandra.yml
    - classpath:/application-redis.yml
    - classpath:/application-monitoring.yml
    - optional:classpath:/application-secret.yml

server:
  port: 8100
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: story-distributor
  webflux:
    format:
      date: iso
      date-time: iso
      time: iso
    base-path: /distributor
  security:
    user:
      name: ksh
      password: ksh
