version: "3.9"

services:
  cassandra:
    image: cassandra:4.0.3
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=512M"
      - "HEAP_NEWSIZE=256M"
    restart: always
    volumes:
      - cassandra_data:/var/lib/cassandra

  redis:
    image: redis:6.0
    command: redis-server --port 6379
    ports:
      - '6381:6379'
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  cassandra_data:
    driver: local
  redis_data:
    driver: local
