### 셋업
GET {{api}}/health/readiness

> {%
    client.test("200 OK", () => {
        client.global.set("ACCOUNT_ID", "seungh0")
        client.global.set("TARGET_ID", "yerim")
        client.global.set("AUTHENTICATION_KEY", "api-key")
    });
%}
