spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-kafka.yml
    - classpath:/application-cassandra.yml
    - optional:classpath:/application-secret.yml

server:
  port: 8100
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: tokki-api-consumer
  webflux:
    format:
      date: iso
      date-time: iso
      time: iso
  kafka:
    consumer:
      group-id: STORY_datacenter_API_CONSUMER
