version: "3.9"

services:
  cassandra:
    container_name: story-cassandra-local
    image: cassandra:4.1
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=512M"
      - "HEAP_NEWSIZE=256M"
    restart: on-failure
    volumes:
      - cassandra_data1:/var/lib/cassandra
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis-1:
    container_name: story-redis-local
    image: redis:6.2-alpine
    command: redis-server --port 6379 --appendonly yes
    ports:
      - '6380:6379'
    restart: on-failure
    volumes:
      - redis_data1:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  zookeeper:
    container_name: story-zookeeper-local
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "22181:2181"
    restart: on-failure
    volumes:
      - zookeeper_data1:/var/lib/zookeeper/data
      - zookeeper_log1:/var/lib/zookeeper/log

  kafka:
    container_name: story-kafka-local
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    restart: on-failure
    volumes:
      - kafka_data1:/var/lib/kafka/data
    healthcheck:
     test: nc -z localhost 9092 || exit -1
     start_period: 15s
     interval: 5s
     timeout: 10s
     retries: 10

  kafka-manager:
    container_name: story-kafka-manager-local
    image: hlebalbau/kafka-manager:stable
    platform: linux/amd64
    depends_on:
      - kafka
      - zookeeper
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: "random-secret"
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    restart: on-failure
    ports:
      - "9000:9000"

volumes:
  cassandra_data1:
    driver: local
  redis_data1:
    driver: local
  kafka_data1:
    driver: local
  zookeeper_data1:
    driver: local
  zookeeper_log1:
    driver: local
