services:
  cassandra-1:
    image: cassandra:5.0
    container_name: story-local-cassandra-1
    ports:
      - "9042:9042"
    environment:
      - "CASSANDRA_SEEDS=cassandra-1"
      - "CASSANDRA_CLUSTER_NAME=cluster"
      - "CASSANDRA_NUM_TOKENS=16"
      - "CASSANDRA_DC=dc1"
      - "CASSANDRA_RACK=rack1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "MAX_HEAP_SIZE=512M"
      - "HEAP_NEWSIZE=256M"
    restart: unless-stopped
    networks:
      - story-local-network
    volumes:
      - cassandra_data-1:/var/lib/cassandra
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra-2:
    image: cassandra:5.0
    container_name: story-local-cassandra-2
    ports:
      - "9043:9042"
    environment:
      - "CASSANDRA_SEEDS=cassandra-1"
      - "CASSANDRA_CLUSTER_NAME=cluster"
      - "CASSANDRA_NUM_TOKENS=16"
      - "CASSANDRA_DC=dc1"
      - "CASSANDRA_RACK=rack2"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "MAX_HEAP_SIZE=512M"
      - "HEAP_NEWSIZE=256M"
    restart: unless-stopped
    networks:
      - story-local-network
    volumes:
      - cassandra_data-2:/var/lib/cassandra
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra-3:
    image: cassandra:5.0
    container_name: story-local-cassandra-3
    ports:
      - "9044:9042"
    environment:
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2"
      - "CASSANDRA_CLUSTER_NAME=cluster"
      - "CASSANDRA_NUM_TOKENS=16"
      - "CASSANDRA_DC=dc1"
      - "CASSANDRA_RACK=rack3"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "MAX_HEAP_SIZE=512M"
      - "HEAP_NEWSIZE=256M"
    restart: unless-stopped
    networks:
      - story-local-network
    volumes:
      - cassandra_data-3:/var/lib/cassandra-3
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: story-redis-local
    command: redis-server --port 6379 --appendonly yes
    ports:
      - '6380:6379'
    restart: unless-stopped
    networks:
      - story-local-network
    volumes:
      - redis_data1:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: story-zookeeper-local
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    restart: unless-stopped
    networks:
      - story-local-network
    volumes:
      - zookeeper_data1:/var/lib/zookeeper/data
      - zookeeper_log1:/var/lib/zookeeper/log
    healthcheck:
      test: nc -z localhost 2181 || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: story-kafka-local
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    restart: unless-stopped
    networks:
      - story-local-network
    volumes:
      - kafka_data1:/var/lib/kafka/data
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    platform: linux/amd64
    container_name: story-kafka-manager-local
    depends_on:
      zookeeper:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: "random-secret"
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    restart: unless-stopped
    networks:
      - story-local-network

volumes:
  cassandra_data-1:
    driver: local
  cassandra_data-2:
    driver: local
  cassandra_data-3:
    driver: local
  redis_data:
    driver: local
  kafka_data:
    driver: local
  zookeeper_data:
    driver: local
  zookeeper_log:
    driver: local

networks:
  story-local-network:
    driver: bridge
