spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-kafka.yml
    - classpath:/application-cassandra.yml
    - classpath:/application-redis.yml
    - optional:classpath:/application-secret.yml

server:
  port: 8000
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: tokki-api
  webflux:
    base-path: /api
    format:
      date: iso
      date-time: iso
      time: iso
