secret:
  cassandra:
    contact-points: 10.113.138.132,10.113.149.132,10.113.139.130
    port: 9042
    keyspace-name: story_platform_dev
    local-datacenter: dc1
    username: will
    password: will
