management:
  server:
    port: 18000
  endpoints:
    web:
      exposure:
        include: prometheus,health
      base-path: /monitoring
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.9,0.99
  tracing:
    sampling:
      probability: 0.1
