spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-kafka.yml
    - classpath:/application-cassandra.yml
    - classpath:/application-redis.yml
    - classpath:/application-monitoring.yml
    - optional:classpath:/application-secret.yml

server:
  port: 8200
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: story-publisher
  webflux:
    base-path: /publisher
    format:
      date: iso
      date-time: iso
      time: iso
  security:
    user:
      name: ksh
      password: ksh
