story:
  kafka:
    default:
      replication-count: 3
    topic:
      subscription:
        name: story-subscription-event-v1
        partition-count: 10
      post:
        name: story-post-event-v1
        partition-count: 10
        dlt:
          enabled: true
        retry:
          attempts: 3
          partition-count: 3
      component:
        name: story-component-event-v1
        partition-count: 3
        dlt:
          enabled: true
        retry:
          attempts: 3
          partition-count: 3
      api-key:
        name: story-api-key-event-v1
        partition-count: 3
        dlt:
          enabled: true
        retry:
          attempts: 3
          partition-count: 3
      purge:
        name: story-purge-event-v1
        partition-count: 3
      feed-fanout:
        name: story-feed-fanout-v1
        partition-count: 10
      feed-mapping:
        name: story-feed-mapping-v1
        partition-count: 3
        dlt:
          enabled: true
        retry:
          attempts: 3
          partition-count: 3
      workspace:
        name: story-workspace-v1
        partition-count: 3
        dlt:
          enabled: true
        retry:
          attempts: 3
          partition-count: 3
      reaction:
        name: story-reaction-v1
        partition-count: 10
logging:
  level:
    org.apache.kafka.clients.consumer.internals: WARN
    org.springframework.kafka.listener.KafkaMessageListenerContainer: WARN
    org.apache.kafka.clients.Metadata: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.common.utils.AppInfoParser: WARN


---
spring.config:
  activate:
    on-profile:
      - local

spring:
  kafka:
    bootstrap-servers: localhost:29092
    admin:
      auto-create: true

story:
  kafka:
    default:
      replication-count: 1

---
spring.config:
  activate:
    on-profile:
      - test

spring:
  kafka:
    bootstrap-servers: localhost:39092
    admin:
      auto-create: true

story:
  kafka:
    default:
      replication-count: 1


---
spring.config:
  activate:
    on-profile:
      - dev

spring:
  kafka:
    bootstrap-servers: 223.130.136.209:9092,110.165.18.231:9092,223.130.138.92:9092
    admin:
      auto-create: true

story:
  kafka:
    default:
      replication-count: 1
