story:
  photo:
    properties:
      IMAGE:
        domain: http://localhost:1000

spring:
  cloud:
    circuitbreaker:
      resilience4j:
        disable-time-limiter: true

resilience4j:
  circuitbreaker:
    metrics:
      enabled: true

logging:
  level:
    com.story.core.support: INFO
