### 리액션을 등록 & 수정합니다
PUT {{api}}/v1/resources/reactions/components/post-like/spaces/{{POST_ID}}
Content-Type: application/json
X-Story-Api-Key: {{API_KEY}}
X-Story-Request-User-Id: {{USER_ID}}

{
    "userId": "{{USER_ID}}",
    "emotions": [
        {
            "emotionId": "1"
        },
        {
            "emotionId": "2"
        }
    ]
}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}


### 대상에 등록된 리액션을 조회합니다
GET {{api}}/v1/resources/reactions/components/post-like/spaces/{{POST_ID}}?includeUnselectedEmotions=true
X-Story-Api-Key: {{API_KEY}}
X-Story-Request-User-Id: {{USER_ID}}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}


### 대상 목록들에 등록된 리액션을 조회합니다
GET {{api}}/v1/resources/reactions/components/post-like/spaces?userId={{USER_ID}}&spaceIds={{POST_ID}}&includeUnselectedEmotions=true
X-Story-Api-Key: {{API_KEY}}
X-Story-Request-User-Id: {{USER_ID}}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}

