### 포스팅 등록
POST {{api}}/v1/posts/components/account-post/spaces/{{ACCOUNT_ID}}/posts
Content-Type: application/json
X-Story-Api-Key: {{AUTHENTICATION_KEY}}
Accept-Language: en

{
    "accountId": "{{ACCOUNT_ID}}",
    "title": "토끼의 소확행 일기",
    "content": "토끼랑 치킨을 먹었따\n히히~",
    "extra": {
      "config": true
    }
}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
        client.global.set("POST_ID", response.body["result"]["postId"])
    });
%}


### 포스팅 수정
PATCH {{api}}/v1/posts/components/account-post/spaces/{{ACCOUNT_ID}}/posts/{{POST_ID}}
Content-Type: application/json
X-Story-Api-Key: {{AUTHENTICATION_KEY}}

{
    "accountId": "{{ACCOUNT_ID}}",
    "title": "변경이 되나요?",
    "content": "변경 되나요오",
    "extra": {
      "config": true
    }
}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}


### 포스팅 삭제
DELETE {{api}}/v1/posts/components/account-post/spaces/{{ACCOUNT_ID}}/posts/{{POST_ID}}?accountId={{ACCOUNT_ID}}
X-Story-Api-Key: {{AUTHENTICATION_KEY}}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}


### 포스팅 조회
GET {{api}}/v1/posts/components/account-post/spaces/{{ACCOUNT_ID}}/posts/{{POST_ID}}
X-Story-Api-Key: {{AUTHENTICATION_KEY}}


### 포스팅 목록 조회
GET {{api}}/v1/posts/components/account-post/spaces/{{ACCOUNT_ID}}/posts?pageSize=2&direction=NEXT&cursor={{POST_ID}}
X-Story-Api-Key: {{AUTHENTICATION_KEY}}
