### 포스팅 등록
POST {{api}}/v1/resources/posts/components/user-home/spaces/{{USER_ID}}/posts
Content-Type: application/json
X-Story-Api-Key: {{API_KEY}}
X-Story-Request-User-Id: {{USER_ID}}
Accept-Language: en
#X-Story-Nonce: {{NONCE}}

{
    "title": "depth 1-1",
    "sections": [
        {
            "sectionType": "TEXT",
            "data": {
                "content": "뽀민데요\n123",
                "priority": 1
            }
        },
        {
            "sectionType": "TEXT",
            "data": {
                "content": "토킨데요\n히히~ 234",
                "priority": 2
            }
        },
        {
            "sectionType": "LINK",
            "data": {
                "priority": 4,
                "link": "https://intro.threedollars.co.kr",
                "extra": {
                    "og:image": "http://localhost:5000/abc.png",
                    "og:title": "뽀미 토키",
                    "og:description": "뽀미랑 토키의 사진입니다"
                }
            }
        }
    ],
    "extra": {
        "allowComment": "false"
    }
}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
        client.global.set("POST_ID", response.body["result"]["postId"])
    });
%}


### 하위 포스팅 등록
POST {{api}}/v1/resources/posts/components/user-home/spaces/{{USER_ID}}/posts
Content-Type: application/json
X-Story-Api-Key: {{API_KEY}}
X-Story-Request-User-Id: {{USER_ID}}
Accept-Language: en
#X-Story-Nonce: {{NONCE}}

{
    "parentId": "{{POST_ID}}",
    "title": "depth 1-1",
    "sections": [
        {
            "sectionType": "TEXT",
            "data": {
                "content": "뻐미\n히히~ 123",
                "priority": 1
            }
        },
        {
            "sectionType": "TEXT",
            "data": {
                "content": "터키\n히히~ 234",
                "priority": 2
            }
        },
        {
            "sectionType": "IMAGE",
            "data": {
                "priority": 3,
                "fileId": 86471063135047680
            }
        },
        {
            "sectionType": "LINK",
            "data": {
                "priority": 4,
                "link": "https://intro.threedollars.co.kr",
                "extra": {
                    "og:image": "http://localhost:5000/abc.png",
                    "og:title": "뽀미 토키",
                    "og:description": "뽀미랑 토키의 사진입니다"
                }
            }
        }
    ]
}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
        client.global.set("POST_ID", response.body["result"]["postId"])
    });
%}

### 포스팅 수정
PATCH {{api}}/v1/resources/posts/components/user-home/spaces/{{USER_ID}}/posts/{{POST_ID}}
Content-Type: application/json
X-Story-Api-Key: {{API_KEY}}
X-Story-Request-User-Id: {{USER_ID}}

{
    "title": "변경이 되나요?",
    "sections": [
        {
            "sectionType": "TEXT",
            "data": {
                "content": "토끼랑 치킨을 먹었따\n히히~ 234",
                "priority": 1
            }
        },
        {
            "sectionType": "LINK",
            "data": {
                "priority": 4,
                "link": "https://intro.threedollars.co.kr",
                "extra": {
                    "og:image": "http://localhost:5000/abc.png",
                    "og:title": "뽀미 토키",
                    "og:description": "뽀미랑 토키의 사진입니다"
                }
            }
        }
    ],
    "extra": {
        "allowComment": "true"
    }
}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}


### 포스팅 조회
GET {{api}}/v1/resources/posts/components/user-home/spaces/{{USER_ID}}/posts/{{POST_ID}}
X-Story-Api-Key: {{API_KEY}}
X-Story-Request-User-Id: {{USER_ID}}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}


### 포스팅 목록 조회 (Root)
GET {{api}}/v1/resources/posts/components/user-home/spaces/{{USER_ID}}/posts?pageSize=10&direction=NEXT&
    sortBy=LATEST
X-Story-Api-Key: {{API_KEY}}
X-Story-Request-User-Id: {{USER_ID}}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}


### 하위 포스팅 목록 조회
GET {{api}}/v1/resources/posts/components/user-home/spaces/{{USER_ID}}/posts?pageSize=10&direction=NEXT&
    sortBy=LATEST&parentId={{POST_ID}}
X-Story-Api-Key: {{API_KEY}}
X-Story-Request-User-Id: {{USER_ID}}


> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}


### 유저가 등록한 포스팅 목록을 조회합니다
GET {{api}}/v1/resources/posts/components/user-home/users/{{USER_ID}}/posts?pageSize=10
X-Story-Api-Key: {{API_KEY}}
X-Story-Request-User-Id: {{USER_ID}}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}


### 포스팅 삭제
DELETE {{api}}/v1/resources/posts/components/user-home/spaces/{{USER_ID}}/posts/{{POST_ID}}
X-Story-Api-Key: {{API_KEY}}
X-Story-Request-User-Id: {{USER_ID}}

> {%
    client.test("200 OK", () => {
        client.assert(response.status === 200, "응답 실패");
    });
%}
