spring:
  data:
    redis:
      port: 6381
      host: localhost
      connect-timeout: 2s

---
spring.config:
  activate:
    on-profile:
      - test

spring:
  redis:
    host: localhost
    port: 6381
