spring:
  data:
    redis:
      connect-timeout: 3000
      timeout: 3000


---
spring.config:
  activate:
    on-profile:
      - local

spring:
  data:
    redis:
      port: 6380
      host: localhost
      database: 0


---
spring.config:
  activate:
    on-profile:
      - test

spring:
  data:
    redis:
      port: 6380
      host: localhost
      database: 1


---
spring.config:
  activate:
    on-profile:
      - dev # TODO: 변경

spring:
  data:
    redis:
      port: 6380
      host: localhost
      database: 2
