spring:
  data:
    redis:
      connect-timeout: 3000
      timeout: 3000


---
spring.config:
  activate:
    on-profile:
      - local
      - test
spring:
  data:
    redis:
      port: 6380
      host: localhost
