story:
  kafka:
    subscription:
      topic: subscription_v1
      group-id: story-worker-subscription
    post:
      topic: post_v1
      group-id: story-worker-post
    subscriber:
      distributor:
        topic: subscriber_distributor_v1
        group-id: story-worker-subscriber-distributor

---
spring.config:
  activate:
    on-profile: local

spring:
  kafka:
    bootstrap-servers: localhost:29092


---
spring.config:
  activate:
    on-profile: dev

spring:
  kafka:
    bootstrap-servers: 118.67.131.30:9092


---
spring.config:
  activate:
    on-profile: test

spring:
  kafka:
    bootstrap-servers: localhost:29092
