story:
  kafka:
    default:
      replication-count: 3
    topic:
      subscription:
        name: story.subscription-event-v1
        partition-count: 10
      post:
        name: story.post-event-v1
        partition-count: 10
        dlt:
          enabled: true
        retry:
          attempts: 3
          partition-count: 3
      component:
        name: story.component-event-v1
        partition-count: 3
        dlt:
          enabled: true
        retry:
          attempts: 3
          partition-count: 3
      authentication:
        name: story.authentication-event-v1
        partition-count: 3
        dlt:
          enabled: true
        retry:
          attempts: 3
          partition-count: 3
      purge:
        name: story.purge-event-v1
        partition-count: 3
      feed:
        name: story.feed-v1
        partition-count: 10
      workspace:
        name: story.workspace-v1
        partition-count: 3
        dlt:
          enabled: true
        retry:
          attempts: 3
          partition-count: 3

logging:
  level:
    org.apache.kafka.clients.consumer.internals: WARN
    org.springframework.kafka.listener.KafkaMessageListenerContainer: WARN
    org.apache.kafka.clients.Metadata: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.common.utils.AppInfoParser: WARN


---
spring.config:
  activate:
    on-profile: local

spring:
  kafka:
    bootstrap-servers: localhost:29092
    admin:
      auto-create: true

story:
  kafka:
    default:
      replication-count: 1


---
spring.config:
  activate:
    on-profile: dev

spring:
  kafka:
    bootstrap-servers: 118.67.131.30:9092
    admin:
      auto-create: false

---
spring.config:
  activate:
    on-profile: test

spring:
  kafka:
    bootstrap-servers: localhost:29092
    admin:
      auto-create: true

story:
  kafka:
    default:
      replication-count: 1

