spring:
  data:
    redis:
      port: 6379
      host: localhost
      connect-timeout: 2s

---
spring.config:
  activate:
    on-profile:
      - test

spring:
  data:
    redis:
      host: localhost
      port: 6379
