story:
  kafka:
    topic:
      subscription: story.subscription-event-v1
      post: story.post-event-v1
      component: story.component-event-v1
      authentication: story.authentication-event-v1
      purge: story.purge-event-v1
      feed: story.subscription-distributor-v1
      workspace: story.workspace-v1

---
spring.config:
  activate:
    on-profile: local

spring:
  kafka:
    bootstrap-servers: localhost:29092
    admin:
      auto-create: false


---
spring.config:
  activate:
    on-profile: dev

spring:
  kafka:
    bootstrap-servers: 118.67.131.30:9092
    admin:
      auto-create: false

---
spring.config:
  activate:
    on-profile: test

spring:
  kafka:
    bootstrap-servers: localhost:29092
    admin:
      auto-create: true
