spring:
  cassandra:
    schema-action: none
    request:
      consistency: quorum
      timeout: 3000
    connection:
      connect-timeout: 5000

---
spring.config:
  activate:
    on-profile: local

spring:
  cassandra:
    keyspace-name: story_platform_local
    contact-points: localhost
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
    port: 9042

logging:
  level:
    org.springframework.data.cassandra.core.cql.CqlTemplate: DEBUG
    org.springframework.data.cassandra.core.cql.ReactiveCqlTemplate: DEBUG

---
spring.config:
  activate:
    on-profile: dev

spring:
  cassandra:
    keyspace-name: ${secret.cassandra.keyspace-name}
    contact-points: ${secret.cassandra.contact-points}
    port: ${secret.cassandra.port}
    local-datacenter: ${secret.cassandra.local-datacenter}
    schema-action: none
    username: ${secret.cassandra.username}
    password: ${secret.cassandra.password}


---
spring.config:
  activate:
    on-profile: test

spring:
  cassandra:
    keyspace-name: story_platform_test
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1

logging:
  level:
    org.springframework.data.cassandra.core.cql.CqlTemplate: DEBUG
    org.springframework.data.cassandra.core.cql.ReactiveCqlTemplate: DEBUG
