story:
  kafka:
    topic:
      subscription:
        event: story.subscription-event-v1
        distributor: story.subscription-distributor-v1
      post:
        event: story.post-event-v1
      component:
        event: story.component-event-v1
      authentication:
        event: story.authentication-event-v1
      purge:
        event: story.purge-event-v1


---
spring.config:
  activate:
    on-profile: local

spring:
  kafka:
    bootstrap-servers: localhost:29092


---
spring.config:
  activate:
    on-profile: dev

spring:
  kafka:
    bootstrap-servers: 118.67.131.30:9092


---
spring.config:
  activate:
    on-profile: test

spring:
  kafka:
    bootstrap-servers: localhost:29092
