story:
  kafka:
    topic:
      subscription: subscription_v1
      post: post_v1

---
spring.config:
  activate:
    on-profile: local

spring:
  kafka:
    bootstrap-servers: localhost:29092


---
spring.config:
  activate:
    on-profile: dev

spring:
  kafka:
    bootstrap-servers: 118.67.131.30:9092


---
spring.config:
  activate:
    on-profile: test

spring:
  kafka:
    bootstrap-servers: localhost:29092
