name: "CI"

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout@v3
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt

      - name: Lint Check
        run: ./gradlew ktlintCheck

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout@v3
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
        timeout-minutes: 3

      - name: Unit Test
        run: ./gradlew unitTest

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout@v3
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
        timeout-minutes: 3

      # Pull the latest image to build, and avoid caching pull-only images.
      # (docker pull is faster than caching in most cases.)
      - name: Docker Compose Pull
        run: docker compose -f "docker/test/docker-compose.yml" pull
        timeout-minutes: 3

      - name: Setup Integration Test Containers
        run: docker compose -f "docker/test/docker-compose.yml" up -d --build --wait
        timeout-minutes: 3

      - name: Integration Test
        run: ./gradlew integrationTest

      - name: Stop Integration Test Containers
        if: always()
        run: docker compose -f "docker/test/docker-compose.yml" down
