name: "CI"

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout@v3
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Integration Test Containers
        run: docker-compose -f "infra/test/docker-compose.yml" up -d --build

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: gradle

      - name: KtLint Check
        run: ./gradlew ktlintCheck

      - name: Test w/ coverage
        run: ./gradlew clean build

      - name: Stop Integration Test Containers
        if: always()
        run: docker-compose -f "infra/test/docker-compose.yml" down
